# Generated by Django 5.2.4 on 2025-08-28 05:58

import capsule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capsule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capsule",
            name="spotify_url",
        ),
        migrations.RemoveField(
            model_name="capsuleitem",
            name="file_type",
        ),
        migrations.AddField(
            model_name="capsuleitem",
            name="mime_type",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="capsuleitem",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=capsule.models.path_to_capsule_item_file,
            ),
        ),
    ]
