# Generated by Django 5.2.4 on 2026-02-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capsule", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capsule",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("draft", "Draft"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="timezone",
            field=models.CharField(max_length=60),
        ),
    ]
