# Generated by Django 5.2.4 on 2025-09-07 17:48

import capsule.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capsule", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="capsule",
            name="body",
        ),
        migrations.AddField(
            model_name="capsule",
            name="delivery_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="capsuleitem",
            name="text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capsuleitem",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to=capsule.models.path_to_capsule_thumbnail,
            ),
        ),
        migrations.AlterField(
            model_name="capsuleitem",
            name="kind",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("image", "Image"),
                    ("video", "Video"),
                    ("audio", "Audio / Voice Note"),
                    ("gif", "GIF"),
                    ("music_link", "Music Streaming App track link"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="capsule",
            index=models.Index(
                fields=["deliver_on", "status"], name="capsule_cap_deliver_4cd053_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="capsuleitem",
            constraint=models.UniqueConstraint(
                fields=("capsule", "position"), name="unique_position"
            ),
        ),
    ]
