# Generated by Django 5.2.4 on 2025-08-31 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capsule", "0002_remove_capsule_spotify_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capsule",
            name="deliver_on",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="capsuleitem",
            name="capsule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capsule_item",
                to="capsule.capsule",
            ),
        ),
    ]
