# Generated by Django 5.2.4 on 2025-08-31 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("capsule", "0003_alter_capsule_deliver_on_alter_capsuleitem_capsule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capsuleitem",
            name="capsule",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="capsule_items",
                to="capsule.capsule",
            ),
        ),
    ]
